#if !canImport(ObjectiveC)
import XCTest

extension PasswordTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PasswordTests = [
        ("testRepassword", testRepassword),
        ("testResalt", testResalt),
        ("testPassword", testPassword),
        ("testSalt", testSalt),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(PasswordTests.__allTests__PasswordTests),
    ]
}
#endif
